// 從 ../src/data/*.js 產生 Kotlin 資料表（唯一來源是網頁版，避免手抄走樣）
//   node tools/gen-data.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..');
const outDir = path.join(here, '..', 'app', 'src', 'main', 'java', 'com', 'dreamrestaurant', 'data');
fs.mkdirSync(outDir, { recursive: true });

const D = await import(pathToFileURL(path.join(root, 'src', 'data', 'index.js')).href);

const esc = (s) =>
  String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');

const str = (s) => `"${esc(s)}"`;
const num = (n) => (Number.isInteger(n) ? `${n}.0` : String(n));
const int = (n) => String(Math.round(n));
const bool = (b) => (b ? 'true' : 'false');

const list = (arr, f) => `listOf(${arr.map(f).join(', ')})`;
const strList = (arr) => list(arr, (s) => str(s));
const dmap = (obj) => {
  const entries = Object.entries(obj);
  if (!entries.length) return 'emptyMap()';
  return `mapOf(${entries.map(([k, v]) => `${str(k)} to ${num(v)}`).join(', ')})`;
};
const smap = (obj) => {
  const entries = Object.entries(obj);
  if (!entries.length) return 'emptyMap()';
  return `mapOf(${entries.map(([k, v]) => `${str(k)} to ${str(v)}`).join(', ')})`;
};
const nullableStrList = (arr) => (arr == null ? 'null' : strList(arr));
const indent = (block) => block.split('\n').join('\n');

function write(name, pkg, header, body) {
  const file = path.join(outDir, name);
  fs.writeFileSync(file, `${header}\n${body}\n`, 'utf8');
  console.log('wrote', path.relative(root, file));
}

/* ------------------------------------------------------------------ DISHES */
{
  const items = D.DISHES.map(
    (d) => `    Dish(
      id = ${str(d.id)},
      name = ${str(d.name)},
      category = ${str(d.category)},
      baseCost = ${int(d.baseCost)},
      expectedPrice = ${int(d.expectedPrice)},
      unlockStars = ${int(d.unlockStars)},
      secret = ${bool(d.secret)},
      tags = ${strList(d.tags)},
      cookTimeDefault = ${int(d.cookTimeDefault)},
      portionDefault = ${int(d.portionDefault)},
      tasteDefault = ${int(d.tasteDefault)},
      gradeDefault = ${int(d.gradeDefault)},
      popularity = ${dmap(d.popularity)},
      desc = ${str(d.desc)}
    )`
  );
  write(
    'DishesData.kt',
    'com.dreamrestaurant.data',
    '// GENERATED by tools/gen-data.mjs — do not edit.\npackage com.dreamrestaurant.data',
    `val DISHES: List<Dish> = listOf(\n${items.join(',\n')}\n)\n\nval DISH_CATEGORIES = ${strList(D.DISH_CATEGORIES)}\n\nval TAG_LIST = ${strList(D.TAG_LIST)}`
  );
}

/* ------------------------------------------------------------------ STAFF */
{
  const items = D.STAFF_POOL.map(
    (s) => `    StaffDef(
      id = ${str(s.id)},
      name = ${str(s.name)},
      role = ${str(s.role)},
      age = ${int(s.age)},
      gender = ${str(s.gender)},
      speed = ${int(s.speed)},
      skill = ${int(s.skill)},
      stamina = ${int(s.stamina)},
      wage = ${int(s.wage)},
      initWage = ${int(s.initWage)},
      specialty = ${str(s.specialty)},
      personality = ${str(s.personality)},
      desc = ${str(s.desc)},
      portrait = Portrait(hair = ${str(s.portrait.hair)}, skin = ${str(s.portrait.skin)}, shirt = ${str(s.portrait.shirt)}, hat = ${int(s.portrait.hat)})
    )`
  );
  write(
    'StaffData.kt',
    'com.dreamrestaurant.data',
    '// GENERATED by tools/gen-data.mjs — do not edit.\npackage com.dreamrestaurant.data',
    `val STAFF_POOL: List<StaffDef> = listOf(\n${items.join(',\n')}\n)`
  );
}

/* -------------------------------------------------------------- LOCATIONS */
{
  const items = D.LOCATIONS.map(
    (l) => `    LocationDef(
      id = ${str(l.id)},
      name = ${str(l.name)},
      city = ${str(l.city)},
      starsRequired = ${int(l.starsRequired)},
      rentPerDay = ${int(l.rentPerDay)},
      baseTraffic = ${num(l.baseTraffic)},
      moveCost = ${int(l.moveCost)},
      gridW = ${int(l.gridW)},
      gridH = ${int(l.gridH)},
      customerMix = ${dmap(l.customerMix)},
      tastePrefs = ${strList(l.tastePrefs)},
      weatherWeights = ${dmap(l.weatherWeights)},
      decorStyle = ${str(l.decorStyle)},
      skyline = ${str(l.skyline)},
      palette = ${smap(l.palette)},
      desc = ${str(l.desc)}
    )`
  );
  write(
    'LocationsData.kt',
    'com.dreamrestaurant.data',
    '// GENERATED by tools/gen-data.mjs — do not edit.\npackage com.dreamrestaurant.data',
    `val LOCATIONS: List<LocationDef> = listOf(\n${items.join(',\n')}\n)`
  );
}

/* -------------------------------------------------------------- FURNITURE */
{
  const items = D.FURNITURE.map(
    (f) => `    FurnitureDef(
      id = ${str(f.id)},
      name = ${str(f.name)},
      category = ${str(f.category)},
      w = ${int(f.w)},
      h = ${int(f.h)},
      price = ${int(f.price)},
      seats = ${int(f.seats)},
      seatFacing = ${strList(f.seatFacing)},
      decorScore = ${int(f.decorScore)},
      style = ${str(f.style)},
      blocks = ${bool(f.blocks)},
      needsAdjacentFloor = ${bool(f.needsAdjacentFloor)},
      durability = ${int(f.durability)},
      desc = ${str(f.desc)}
    )`
  );
  write(
    'FurnitureData.kt',
    'com.dreamrestaurant.data',
    '// GENERATED by tools/gen-data.mjs — do not edit.\npackage com.dreamrestaurant.data',
    `val FURNITURE: List<FurnitureDef> = listOf(\n${items.join(',\n')}\n)`
  );
}

/* ----------------------------------------------------------------- EVENTS */
{
  const items = D.EVENTS.map((e) => {
    const f = e.effects || {};
    const rep = f.reputation || {};
    return `    EventDef(
      id = ${str(e.id)},
      name = ${str(e.name)},
      kind = ${str(e.kind)},
      weight = ${int(e.weight)},
      minStars = ${int(e.minStars)},
      maxStars = ${int(e.maxStars)},
      locations = ${nullableStrList(e.locations)},
      onlyWhileOpen = ${bool(e.onlyWhileOpen)},
      mitigateBy = ${nullableStrList(e.mitigateBy)},
      message = ${str(e.message)},
      log = ${str(e.log)},
      effects = EventEffects(
        fame = ${f.fame == null ? '0' : int(f.fame)},
        repCommunity = ${rep.community == null ? '0' : int(rep.community)},
        repOutside = ${rep.outside == null ? '0' : int(rep.outside)},
        moodAll = ${f.moodAll == null ? '0' : int(f.moodAll)},
        trafficMul = ${f.trafficMul == null ? '1.0' : num(f.trafficMul)},
        trafficMulMinutes = ${f.trafficMulMinutes == null ? '0' : int(f.trafficMulMinutes)},
        cash = ${f.cash == null ? '0' : int(f.cash)},
        supplierPriceMul = ${f.supplierPriceMul == null ? '1.0' : num(f.supplierPriceMul)},
        stockLoss = ${f.stockLoss == null ? '0.0' : num(f.stockLoss)},
        damage = ${f.damage == null ? 'null' : str(f.damage)}
      )
    )`;
  });
  write(
    'EventsData.kt',
    'com.dreamrestaurant.data',
    '// GENERATED by tools/gen-data.mjs — do not edit.\npackage com.dreamrestaurant.data',
    `val EVENTS: List<EventDef> = listOf(\n${items.join(',\n')}\n)`
  );
}

console.log('done:', D.DISHES.length, 'dishes,', D.STAFF_POOL.length, 'staff,', D.LOCATIONS.length, 'locations,', D.FURNITURE.length, 'furniture,', D.EVENTS.length, 'events');
